### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by materialwork** [materialwork/Old-move#1]
- [ ] Implement move logs
- [ ] Allow for custom lists
- [ ] Allow for custom oldlists
- [ ] Make it collapsible
- [ ] Add move reviews
